# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    # Add assignees
    assignees:
      - "math-fehr"
      - "georgebisbas"
    commit-message:
      prefix: "uv prod"
      prefix-development: "uv dev"
      include: "scope"
